name: Test
on: [push]
jobs:
  lint-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v4
      with:
        python-version: '3.9'
    - run: python -m pip install -e ".[dev]"
    - run: pytest tests

